package main

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"relaygo/bridge"
	"relaygo/mcp"
)

// SkillLister resolves the tool list visible to a given project token.
// Implemented by *appRouter. Lives in skills.go so the regen path can be
// driven both in-process (settings hooks) and via the bridge.
type SkillLister interface {
	ListTools(ctx context.Context, token string) (json.RawMessage, error)
}

// RegenMode controls when EmitSkill writes the SKILL.md file. Values mirror
// the wire constants in bridge.RegenSkills* so callers across the bridge use
// the same vocabulary.
type RegenMode string

const (
	RegenAlways       RegenMode = bridge.RegenSkillsAlways
	RegenSkipIfExists RegenMode = bridge.RegenSkillsSkipIfExists
	RegenNever        RegenMode = bridge.RegenSkillsNever
)

// skillFileName is the filename agentskills.io agents look for.
const skillFileName = "SKILL.md"

// EmitSkill renders a SKILL.md for the project's currently-allowed tools and
// writes it to dir/SKILL.md, creating parent dirs as needed. The project's
// plaintext token is used to query the live tool list and is NEVER written
// into the file. Returns the absolute path of the written file.
func EmitSkill(ctx context.Context, lister SkillLister, proj Project, dir string, mode RegenMode) (string, error) {
	if proj.Token == "" {
		return "", fmt.Errorf("project %q has no token", proj.Name)
	}
	if dir == "" {
		return "", fmt.Errorf("skill dir is empty")
	}

	abs, err := filepath.Abs(dir)
	if err != nil {
		return "", fmt.Errorf("resolve skill dir: %w", err)
	}
	target := filepath.Join(abs, skillFileName)

	switch mode {
	case RegenNever:
		return target, nil
	case RegenSkipIfExists:
		if _, err := os.Stat(target); err == nil {
			return target, nil
		}
	case RegenAlways, "":
		// fall through
	default:
		return "", fmt.Errorf("unknown regen mode %q", mode)
	}

	raw, err := lister.ListTools(ctx, proj.Token)
	if err != nil {
		return "", fmt.Errorf("list tools: %w", err)
	}
	var tools []mcp.Tool
	if err := json.Unmarshal(raw, &tools); err != nil {
		return "", fmt.Errorf("parse tools: %w", err)
	}

	body := []byte(renderSkillMd(proj, tools))

	// Skip the write when content is identical so file watchers (eve, IDEs,
	// fsnotify-based reload loops) don't wake on every PTY launch.
	if existing, err := os.ReadFile(target); err == nil && bytes.Equal(existing, body) {
		return target, nil
	}

	if err := os.MkdirAll(abs, 0o755); err != nil {
		return "", fmt.Errorf("mkdir skill dir: %w", err)
	}
	if err := os.WriteFile(target, body, 0o644); err != nil {
		return "", fmt.Errorf("write skill file: %w", err)
	}
	return target, nil
}

// RemoveSkill removes the relay-managed skill directory. Safe to call when
// the directory does not exist.
func RemoveSkill(dir string) error {
	if dir == "" {
		return nil
	}
	abs, err := filepath.Abs(dir)
	if err != nil {
		return fmt.Errorf("resolve skill dir: %w", err)
	}
	if filepath.Base(abs) != "relay" {
		return fmt.Errorf("refusing to remove non-relay skill dir: %s", abs)
	}
	if err := os.RemoveAll(abs); err != nil {
		return fmt.Errorf("remove skill dir: %w", err)
	}
	return nil
}

// renderSkillMd produces a SKILL.md body. Token is never included.
func renderSkillMd(proj Project, tools []mcp.Tool) string {
	sorted := make([]mcp.Tool, len(tools))
	copy(sorted, tools)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Name < sorted[j].Name })

	// Use the absolute path of the running relay binary so the agent does
	// not have to grep PATH or guess (/Applications/Relay.app/Contents/MacOS/
	// is not on PATH by default). Regen at each launch keeps this fresh
	// across reinstalls/moves.
	relayBin := resolveRelayBin()

	var b strings.Builder
	fmt.Fprintf(&b, "---\n")
	fmt.Fprintf(&b, "description: %s project tools — invoke via the relay CLI. Use when the user asks to do something that matches one of the tools listed below.\n", yamlEscape(proj.Name))
	fmt.Fprintf(&b, "allowed-tools: Bash(%s mcp call *)\n", relayBin)
	fmt.Fprintf(&b, "---\n\n")
	fmt.Fprintf(&b, "<!-- Generated by relay. Do not edit. Regenerated on PTY launch and project changes. -->\n\n")
	fmt.Fprintf(&b, "# relay tools for %s\n\n", proj.Name)
	fmt.Fprintf(&b, "This skill exposes the %s project's MCP tools through the relay CLI. ", proj.Name)
	fmt.Fprintf(&b, "`RELAY_TOKEN` is already set in the environment for this session — do not paste tokens into prompts.\n\n")
	fmt.Fprintf(&b, "**Relay binary path:** `%s` (use this absolute path — relay is not on $PATH by default)\n\n", relayBin)

	fmt.Fprintf(&b, "## Invocation\n\n")
	fmt.Fprintf(&b, "```\n%s mcp call --list                          # enumerate tools\n%s mcp call --list --schema                 # enumerate with input schemas (JSON)\n%s mcp call --tool <NAME> --args '<JSON>'   # invoke a tool\n```\n\n", relayBin, relayBin, relayBin)

	if len(sorted) == 0 {
		fmt.Fprintf(&b, "## Available tools\n\nNo tools are currently available for this project. Check the project's allowed MCPs in the relay Settings UI.\n")
		return b.String()
	}

	fmt.Fprintf(&b, "## Available tools (%d)\n\n", len(sorted))
	for _, t := range sorted {
		desc := strings.TrimSpace(t.Description)
		if desc == "" {
			desc = "(no description)"
		}
		fmt.Fprintf(&b, "- **%s** — %s\n", t.Name, oneLine(desc))
	}
	fmt.Fprintf(&b, "\nFor parameter schemas, run `%s mcp call --list --schema`.\n", relayBin)
	return b.String()
}

// resolveRelayBin returns the absolute path of the running relay binary,
// following symlinks. Falls back to the bare command name if anything fails
// — agents can still find it via PATH if it happens to be there.
func resolveRelayBin() string {
	exe, err := os.Executable()
	if err != nil {
		return "relay"
	}
	if resolved, err := filepath.EvalSymlinks(exe); err == nil {
		return resolved
	}
	return exe
}

// yamlEscape escapes a string for inclusion as a YAML scalar value in
// frontmatter. Only handles characters that would break a single-line value.
func yamlEscape(s string) string {
	s = strings.ReplaceAll(s, "\\", "\\\\")
	s = strings.ReplaceAll(s, "\"", "\\\"")
	s = strings.ReplaceAll(s, "\n", " ")
	return s
}

// oneLine collapses internal newlines so a multi-line description renders as
// a single bullet entry.
func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\r\n", " ")
	s = strings.ReplaceAll(s, "\n", " ")
	for strings.Contains(s, "  ") {
		s = strings.ReplaceAll(s, "  ", " ")
	}
	return s
}
