// Package webassets owns the generated document embedded in Relay.app.
package webassets

import _ "embed"

// SettingsHTML is the settings WebView document generated by web/gen.
//
//go:embed settings.html
var SettingsHTML string
